### ISSUE TITLE
Hata var

### ISSUE THREAD

**Issue by Gercekefsane** [AnwarMEQOR/Edu.Emails#2]
handler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80

gibi hata kodları mevcut.

**Comment by kaanmutlu17** [comment]
> handler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80
> 
> gibi hata kodları mevcut.

Adam yabancı ingilizce yaz öyle görür

**Comment by AnwarMEQOR** [comment]
Hi. Please try to speak English next time. 
The problem is with your Chrome version which isn't compatible with the chromedriver version. 
Check this website to download the compatible version: https://chromedriver.chromium.org/
